DROP DATABASE IF EXISTS db;
DROP USER IF EXISTS `restadmin`@`%`;
CREATE DATABASE IF NOT EXISTS db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `restadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'root';
GRANT ALL PRIVILEGES ON db.* TO `restadmin`@`%`;
FLUSH PRIVILEGES;