DROP DATABASE IF EXISTS db;
DROP USER IF EXISTS `dbadmin`@`%`;
CREATE DATABASE IF NOT EXISTS db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `dbadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'PASSWORD_TO_BE_REPLACED';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `db`.* TO `dbadmin`@`%`;